//! Pushouts and finite colimits of framed-poset embeddings.

use std::collections::HashSet;
use std::sync::Arc;

use petgraph::unionfind::UnionFind;

use crate::embedding::Embedding;
use crate::intset::{self, IntSet};
use crate::isomorphism::isomorphisms;
use crate::poset::{FramedPoset, Sign, boundary};

/// Binary pushout result.
#[derive(Debug, Clone)]
pub struct Pushout {
    pub tip: Arc<FramedPoset>,
    pub inl: Embedding,
    pub inr: Embedding,
}

/// One extension attached to a base along a shared domain.
#[derive(Debug, Clone, Copy)]
pub struct Span<'a> {
    pub into_base: &'a Embedding,
    pub into_ext: &'a Embedding,
}

/// Multi-pushout result.
#[derive(Debug, Clone)]
pub struct MultiPushout {
    pub tip: Arc<FramedPoset>,
    pub inl: Embedding,
    pub inrs: Vec<Embedding>,
}

/// One span in a finite diagram of closed embeddings.
#[derive(Debug, Clone, Copy)]
pub struct ColimitSpan<'a> {
    pub left: usize,
    pub right: usize,
    pub into_left: &'a Embedding,
    pub into_right: &'a Embedding,
}

/// A finite colimit together with its canonical injections.
#[derive(Debug, Clone)]
pub struct FiniteColimit {
    pub tip: Arc<FramedPoset>,
    pub injections: Vec<Embedding>,
}

/// Paste two framed posets along a uniquely isomorphic directional boundary.
///
/// The output `direction` boundary of `first` is identified with the input
/// `direction` boundary of `second`. The left and right pushout injections
/// therefore have `first` and `second` as their respective domains.
///
/// # Panics
///
/// Panics unless there is exactly one signed, basis-preserving isomorphism
/// from the output boundary of `first` to the input boundary of `second`.
pub fn paste_along_boundary(
    first: &Arc<FramedPoset>,
    second: &Arc<FramedPoset>,
    direction: usize,
) -> Pushout {
    let (output_boundary, output_into_first) = boundary(Sign::Output, direction, first);
    let (input_boundary, input_into_second) = boundary(Sign::Input, direction, second);

    let mut boundary_isomorphisms = isomorphisms(&output_boundary, &input_boundary);
    assert_eq!(
        boundary_isomorphisms.len(),
        1,
        "direction {direction} boundaries must have exactly one isomorphism"
    );

    let boundary_isomorphism = boundary_isomorphisms.pop().unwrap();
    let output_into_second = Embedding::compose(&boundary_isomorphism, &input_into_second);
    debug_assert!(Arc::ptr_eq(&output_into_first.dom, &output_into_second.dom));

    pushout(&output_into_first, &output_into_second)
}

/// Compute a binary pushout of embeddings.
pub fn pushout(f: &Embedding, g: &Embedding) -> Pushout {
    let size_sum = |x: &FramedPoset| x.sizes().iter().sum::<usize>();
    let (base_emb, ext_emb, swapped) = if size_sum(&f.cod) >= size_sum(&g.cod) {
        (f, g, false)
    } else {
        (g, f, true)
    };

    let mp = multi_pushout(
        &base_emb.cod,
        &[Span {
            into_base: base_emb,
            into_ext: ext_emb,
        }],
    );
    let inr = mp
        .inrs
        .into_iter()
        .next()
        .expect("one span has one right injection");

    if swapped {
        Pushout {
            tip: mp.tip,
            inl: inr,
            inr: mp.inl,
        }
    } else {
        Pushout {
            tip: mp.tip,
            inl: mp.inl,
            inr,
        }
    }
}

/// Compute the colimit of a base with any number of extensions.
pub fn multi_pushout(base: &Arc<FramedPoset>, spans: &[Span<'_>]) -> MultiPushout {
    let mut objects = Vec::with_capacity(spans.len() + 1);
    objects.push(Arc::clone(base));
    objects.extend(spans.iter().map(|span| Arc::clone(&span.into_ext.cod)));
    let colimit_spans: Vec<_> = spans
        .iter()
        .enumerate()
        .map(|(index, span)| ColimitSpan {
            left: 0,
            right: index + 1,
            into_left: span.into_base,
            into_right: span.into_ext,
        })
        .collect();
    let colimit = finite_colimit(&objects, &colimit_spans);
    let mut injections = colimit.injections.into_iter();
    let inl = injections.next().expect("the base has one injection");
    let inrs = injections.collect();

    MultiPushout {
        tip: colimit.tip,
        inl,
        inrs,
    }
}

/// Compute a finite colimit generated by spans of closed embeddings.
///
/// Each span identifies two images of its common domain. The canonical maps
/// from `objects` into the result must remain injective and closed. Diagram
/// validity and compatibility of the identified incidence data are checked in
/// debug builds.
pub fn finite_colimit(objects: &[Arc<FramedPoset>], spans: &[ColimitSpan<'_>]) -> FiniteColimit {
    debug_assert!(finite_colimit_diagram_well_formed(objects, spans));

    let object_sizes: Vec<_> = objects.iter().map(|object| object.sizes()).collect();
    let mut next_global = 0usize;
    let global_offsets: Vec<Vec<usize>> = object_sizes
        .iter()
        .map(|sizes| {
            sizes
                .iter()
                .map(|&size| {
                    let offset = next_global;
                    next_global += size;
                    offset
                })
                .collect()
        })
        .collect();
    let mut classes = UnionFind::<usize>::new(next_global);

    for span in spans {
        for (dim, level) in span.into_left.map.iter().enumerate() {
            for (domain_pos, &left_pos) in level.iter().enumerate() {
                let right_pos = span.into_right.map[dim][domain_pos];
                classes.union(
                    global_offsets[span.left][dim] + left_pos,
                    global_offsets[span.right][dim] + right_pos,
                );
            }
        }
    }

    let levels = object_sizes.iter().map(Vec::len).max().unwrap_or(0);
    let mut quotient_basis: Vec<Vec<IntSet>> = vec![Vec::new(); levels];
    let mut quotient_cells = vec![None; next_global];
    let mut object_maps: Vec<Vec<Vec<usize>>> = object_sizes
        .iter()
        .map(|sizes| sizes.iter().map(|&size| vec![0; size]).collect())
        .collect();

    for dim in 0..levels {
        for (object_index, object) in objects.iter().enumerate() {
            let Some(map_level) = object_maps[object_index].get_mut(dim) else {
                continue;
            };
            for (pos, image) in map_level.iter_mut().enumerate() {
                let root = classes.find_mut(global_offsets[object_index][dim] + pos);
                let quotient = if let Some((root_dim, root_pos)) = quotient_cells[root] {
                    debug_assert_eq!(root_dim, dim);
                    debug_assert_eq!(quotient_basis[dim][root_pos], *object.basis_of(dim, pos));
                    root_pos
                } else {
                    let quotient = quotient_basis[dim].len();
                    quotient_basis[dim].push(object.basis_of(dim, pos).clone());
                    quotient_cells[root] = Some((dim, quotient));
                    quotient
                };
                *image = quotient;
            }
        }
    }

    debug_assert!(canonical_maps_are_injective(&object_maps));

    let mut quotient_faces_in: Vec<Vec<IntSet>> = quotient_basis
        .iter()
        .map(|level| vec![vec![]; level.len()])
        .collect();
    let mut quotient_faces_out = quotient_faces_in.clone();
    let mut defined: Vec<Vec<bool>> = quotient_basis
        .iter()
        .map(|level| vec![false; level.len()])
        .collect();

    for (object_index, object) in objects.iter().enumerate() {
        for (dim, &size) in object_sizes[object_index].iter().enumerate() {
            for pos in 0..size {
                let quotient = object_maps[object_index][dim][pos];
                if defined[dim][quotient] {
                    #[cfg(debug_assertions)]
                    {
                        let mapped_in =
                            mapped_faces(object, &object_maps[object_index], Sign::Input, dim, pos);
                        let mapped_out = mapped_faces(
                            object,
                            &object_maps[object_index],
                            Sign::Output,
                            dim,
                            pos,
                        );
                        debug_assert_eq!(quotient_faces_in[dim][quotient], mapped_in);
                        debug_assert_eq!(quotient_faces_out[dim][quotient], mapped_out);
                    }
                    continue;
                }

                quotient_faces_in[dim][quotient] =
                    mapped_faces(object, &object_maps[object_index], Sign::Input, dim, pos);
                quotient_faces_out[dim][quotient] =
                    mapped_faces(object, &object_maps[object_index], Sign::Output, dim, pos);
                defined[dim][quotient] = true;
            }
        }
    }

    while quotient_basis.last().is_some_and(Vec::is_empty) {
        quotient_basis.pop();
        quotient_faces_in.pop();
        quotient_faces_out.pop();
    }
    let tip = Arc::new(FramedPoset::from_faces(
        quotient_basis,
        quotient_faces_in,
        quotient_faces_out,
    ));
    let injections: Vec<Embedding> = objects
        .iter()
        .zip(object_maps)
        .map(|(object, map)| Embedding::from_map(Arc::clone(object), Arc::clone(&tip), map))
        .collect();
    debug_assert!(injections.iter().all(Embedding::is_closed));

    FiniteColimit { tip, injections }
}

fn mapped_faces(
    object: &FramedPoset,
    object_map: &[Vec<usize>],
    sign: Sign,
    dim: usize,
    pos: usize,
) -> IntSet {
    if dim == 0 {
        vec![]
    } else {
        intset::collect_sorted(
            object
                .faces_of(sign, dim, pos)
                .iter()
                .map(|&face| object_map[dim - 1][face]),
        )
    }
}

fn finite_colimit_diagram_well_formed(
    objects: &[Arc<FramedPoset>],
    spans: &[ColimitSpan<'_>],
) -> bool {
    spans.iter().all(|span| {
        span.left < objects.len()
            && span.right < objects.len()
            && FramedPoset::equal(&span.into_left.dom, &span.into_right.dom)
            && FramedPoset::equal(&span.into_left.cod, &objects[span.left])
            && FramedPoset::equal(&span.into_right.cod, &objects[span.right])
            && span.into_left.is_closed()
            && span.into_right.is_closed()
    })
}

fn canonical_maps_are_injective(maps: &[Vec<Vec<usize>>]) -> bool {
    maps.iter().all(|map| {
        map.iter().all(|level| {
            let unique: HashSet<_> = level.iter().copied().collect();
            unique.len() == level.len()
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::embedding::NO_PREIMAGE;

    fn point() -> Arc<FramedPoset> {
        Arc::new(FramedPoset::point())
    }

    fn arrow() -> Arc<FramedPoset> {
        Arc::new(FramedPoset::from_faces(
            vec![vec![vec![], vec![]], vec![vec![0]]],
            vec![vec![vec![], vec![]], vec![vec![0]]],
            vec![vec![vec![], vec![]], vec![vec![1]]],
        ))
    }

    fn endpoint_embedding(endpoint: usize, cod: Arc<FramedPoset>) -> Embedding {
        let dom = point();
        let map = vec![vec![endpoint]];
        let mut inv = vec![vec![NO_PREIMAGE; 2], vec![NO_PREIMAGE; 1]];
        inv[0][endpoint] = 0;
        Embedding::make(dom, cod, map, inv)
    }

    #[test]
    fn pushout_pastes_two_arrows() {
        let left = arrow();
        let right = arrow();
        let out_left = endpoint_embedding(1, Arc::clone(&left));
        let in_right = endpoint_embedding(0, Arc::clone(&right));

        let po = pushout(&out_left, &in_right);

        assert_eq!(po.tip.sizes(), vec![3, 2]);
        assert_eq!(po.inl.map, vec![vec![0, 1], vec![0]]);
        assert_eq!(po.inr.map, vec![vec![1, 2], vec![1]]);
        assert_eq!(po.tip.basis_of(1, 0), &vec![0]);
        assert_eq!(po.tip.basis_of(1, 1), &vec![0]);
        assert_eq!(po.tip.faces_of(Sign::Input, 1, 1), &vec![1]);
        assert_eq!(po.tip.faces_of(Sign::Output, 1, 1), &vec![2]);
    }

    #[test]
    fn pastes_two_arrows_along_their_unique_directional_boundaries() {
        let first = arrow();
        let second = arrow();

        let pasted = paste_along_boundary(&first, &second, 0);

        assert_eq!(pasted.tip.sizes(), vec![3, 2]);
        assert_eq!(pasted.inl.dom.sizes(), vec![2, 1]);
        assert_eq!(pasted.inr.dom.sizes(), vec![2, 1]);
    }

    #[test]
    fn finite_colimit_handles_non_star_diagrams() {
        let objects = vec![point(), point(), point()];
        let zero_to_zero = Embedding::id(Arc::clone(&objects[0]));
        let zero_to_one = Embedding::id(Arc::clone(&objects[1]));
        let one_to_one = Embedding::id(Arc::clone(&objects[1]));
        let one_to_two = Embedding::id(Arc::clone(&objects[2]));

        let colimit = finite_colimit(
            &objects,
            &[
                ColimitSpan {
                    left: 0,
                    right: 1,
                    into_left: &zero_to_zero,
                    into_right: &zero_to_one,
                },
                ColimitSpan {
                    left: 1,
                    right: 2,
                    into_left: &one_to_one,
                    into_right: &one_to_two,
                },
            ],
        );

        assert_eq!(colimit.tip.sizes(), vec![1]);
        assert_eq!(colimit.injections.len(), 3);
        assert!(colimit.injections.iter().all(Embedding::is_isomorphism));
    }

    #[cfg(debug_assertions)]
    #[test]
    #[should_panic]
    fn finite_colimit_rejects_a_noninjective_canonical_map_in_debug() {
        let edge = arrow();
        let connector = point();
        let edge_input = endpoint_embedding(0, Arc::clone(&edge));
        let edge_output = endpoint_embedding(1, Arc::clone(&edge));
        let connector_first = Embedding::id(Arc::clone(&connector));
        let connector_second = Embedding::id(Arc::clone(&connector));

        let _ = finite_colimit(
            &[edge, connector],
            &[
                ColimitSpan {
                    left: 0,
                    right: 1,
                    into_left: &edge_input,
                    into_right: &connector_first,
                },
                ColimitSpan {
                    left: 0,
                    right: 1,
                    into_left: &edge_output,
                    into_right: &connector_second,
                },
            ],
        );
    }

    #[cfg(debug_assertions)]
    #[test]
    #[should_panic]
    fn pushout_detects_glued_basis_mismatch_in_debug() {
        let base = Arc::new(FramedPoset::from_faces(
            vec![vec![vec![], vec![]], vec![vec![0]]],
            vec![vec![vec![], vec![]], vec![vec![0]]],
            vec![vec![vec![], vec![]], vec![vec![1]]],
        ));
        let ext = Arc::new(FramedPoset::from_faces(
            vec![vec![vec![], vec![]], vec![vec![1]]],
            vec![vec![vec![], vec![]], vec![vec![0]]],
            vec![vec![vec![], vec![]], vec![vec![1]]],
        ));
        let dom = Arc::new(FramedPoset::from_faces(
            vec![vec![vec![]], vec![vec![0]]],
            vec![vec![vec![]], vec![vec![0]]],
            vec![vec![vec![]], vec![vec![]]],
        ));

        let into_base = Embedding {
            dom: Arc::clone(&dom),
            cod: Arc::clone(&base),
            map: vec![vec![0], vec![0]],
            inv: vec![vec![0, NO_PREIMAGE], vec![0]],
        };
        let into_ext = Embedding {
            dom,
            cod: Arc::clone(&ext),
            map: vec![vec![0], vec![0]],
            inv: vec![vec![0, NO_PREIMAGE], vec![0]],
        };

        let _ = multi_pushout(
            &base,
            &[Span {
                into_base: &into_base,
                into_ext: &into_ext,
            }],
        );
    }
}
